version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: lint-cache-{{ checksum "package.json" }}-v01
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: lint-cache-{{ checksum "package.json" }}-v01
          paths:
            - ./node_modules
      - run: 
          name: Lint
          command: npm run eslint 
  test:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: test-cache-{{ checksum "package.json" }}-v01
      - run:
          name: Setup Dependencies
          command: npm ci
      - save_cache:
          key: test-cache-{{ checksum "package.json" }}-v01
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ./node_modules
      - run: 
          name: Setup build
          command: npm run build
      - run: 
          name: Start Next
          command: npm run start    
          background: true
      - run: 
          name: Run Cypress
          command: $(npm bin)/cypress run 
  deploy: 
    docker:
      - image: circleci/node:10.15
    steps: 
      - checkout
      - run: 
          name: Install Now
          command: npm install --production now
      - run:
           name: Deploy
           command: $(npm bin)/now --token $ZEIT_NOW_TOKEN 
      - run: 
            name: Create Alias
            command: $(npm bin)/now alias --token $ZEIT_NOW_TOKEN

workflows:
  version: 2
  code_quality:
    jobs:
      - lint
      - test  
      - deploy: 
          requires:
            - lint 
            - test     
