version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: lint-cache-{{ checksum "package.json" }}-v01
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: lint-cache-{{ checksum "package.json" }}-v01
          paths:
            - ./node_modules
      - run: 
          name: Lint
          command: npm run eslint
  deploy: 
    docker:
      - image: circleci/node:10.15
    steps: 
      - checkout
      - run: 
          name: Install Now
          command: npm install --production now
      - run:
           name: Deploy
           command: $(npm bin)/now --token $ZEIT_NOW_TOKEN 
      - run: 
            name: Create Alias
            command: $(npm bin)/now alias --token $ZEIT_NOW_TOKEN

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint
      - test  
      - deploy: 
          requires:
            - lint 
            - test     
